// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__CANPACKETS_H__
#define __BITPROTO__CANPACKETS_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef uint8_t SensorType; // 4bit

#define PRESSURE_TRANSDUCER 0
#define LOAD_CELL 1
#define THERMAL_COUPLE 2

typedef uint8_t NodeType; // 4bit

#define PRESSURE_TRANSDUCER 0
#define LOAD_CELL 1
#define THERMAL_COUPLE 2
#define SOLENOID 3

// The stages of the rocket firing.
typedef uint8_t Stage; // 4bit

#define METHANOL_PRESSURIZATION 0
#define AIR_PRESSURIZATION 1
#define FIRE_NO_IGNITION 2
#define FIRE_WITH_IGNITION 3
#define PURGE 4
#define CLOSE 5

// Whether a solenoid is open or closed.
typedef uint8_t SolenoidState; // 1bit

#define CLOSED 0
#define OPEN 1

typedef uint8_t ID; // 8bit

// Number of bytes to encode struct SolenoidStatePacket
#define BYTES_LENGTH_SOLENOID_STATE_PACKET 2

// Must be repeated every 20ms, otherwise the solenoid will be closed. (Sent by the mainland.)
// Cannot be sent at the same time as a staging packet, although multiple of these can be sent in sequence.
// ID: 0x02
struct SolenoidStatePacket {
    ID id; // 8bit
    SolenoidState state; // 1bit
};

// Number of bytes to encode struct StagePacket
#define BYTES_LENGTH_STAGE_PACKET 1

// Must be repeated every 20ms, otherwise the solenoids will be closed. (Sent by the mainland.)
// ID: 0x01
struct StagePacket {
    bool system_ready; // 1bit
    Stage stage; // 4bit
};

// Number of bytes to encode struct PowerPacket
#define BYTES_LENGTH_POWER_PACKET 1

// Must be repeated every 20ms, otherwise the power will be cut to all solenoids. (Sent by the mainland.)
// ID: 0x00
struct PowerPacket {
    bool system_powered; // 1bit
};

// Number of bytes to encode struct BlinkPacket
#define BYTES_LENGTH_BLINK_PACKET 1

// Causes a Island node to blink it's USER LED for 5 seconds.
// ID: 0x06
struct BlinkPacket {
    ID node_id; // 8bit
};

// Number of bytes to encode struct SensorDataPacket
#define BYTES_LENGTH_SENSOR_DATA_PACKET 6

// ID: 0x03
struct SensorDataPacket {
    ID node_id; // 8bit
    uint8_t sensor_id; // 4bit
    SensorType sensor_type; // 4bit
    uint32_t sensor_data; // 32bit
};

// Number of bytes to encode struct PongPacket
#define BYTES_LENGTH_PONG_PACKET 2

// Returned by all Island nodes, identifying their ID and their sensor type.
// ID: 0x05
struct PongPacket {
    ID node_id; // 8bit
    NodeType node_type; // 4bit
};

// Encode struct SolenoidStatePacket to given buffer s.
int EncodeSolenoidStatePacket(struct SolenoidStatePacket *m, unsigned char *s);
// Decode struct SolenoidStatePacket from given buffer s.
int DecodeSolenoidStatePacket(struct SolenoidStatePacket *m, unsigned char *s);
// Format struct SolenoidStatePacket to a json format string.
int JsonSolenoidStatePacket(struct SolenoidStatePacket *m, char *s);

// Encode struct StagePacket to given buffer s.
int EncodeStagePacket(struct StagePacket *m, unsigned char *s);
// Decode struct StagePacket from given buffer s.
int DecodeStagePacket(struct StagePacket *m, unsigned char *s);
// Format struct StagePacket to a json format string.
int JsonStagePacket(struct StagePacket *m, char *s);

// Encode struct PowerPacket to given buffer s.
int EncodePowerPacket(struct PowerPacket *m, unsigned char *s);
// Decode struct PowerPacket from given buffer s.
int DecodePowerPacket(struct PowerPacket *m, unsigned char *s);
// Format struct PowerPacket to a json format string.
int JsonPowerPacket(struct PowerPacket *m, char *s);

// Encode struct BlinkPacket to given buffer s.
int EncodeBlinkPacket(struct BlinkPacket *m, unsigned char *s);
// Decode struct BlinkPacket from given buffer s.
int DecodeBlinkPacket(struct BlinkPacket *m, unsigned char *s);
// Format struct BlinkPacket to a json format string.
int JsonBlinkPacket(struct BlinkPacket *m, char *s);

// Encode struct SensorDataPacket to given buffer s.
int EncodeSensorDataPacket(struct SensorDataPacket *m, unsigned char *s);
// Decode struct SensorDataPacket from given buffer s.
int DecodeSensorDataPacket(struct SensorDataPacket *m, unsigned char *s);
// Format struct SensorDataPacket to a json format string.
int JsonSensorDataPacket(struct SensorDataPacket *m, char *s);

// Encode struct PongPacket to given buffer s.
int EncodePongPacket(struct PongPacket *m, unsigned char *s);
// Decode struct PongPacket from given buffer s.
int DecodePongPacket(struct PongPacket *m, unsigned char *s);
// Format struct PongPacket to a json format string.
int JsonPongPacket(struct PongPacket *m, char *s);

void BpXXXProcessID(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatID(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessSolenoidStatePacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatSolenoidStatePacket(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessStagePacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatStagePacket(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPowerPacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPowerPacket(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessBlinkPacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBlinkPacket(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessSensorDataPacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatSensorDataPacket(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPongPacket(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPongPacket(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif