// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "canpackets_bp.h"

void BpXXXProcessID(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpUint(8, sizeof(uint8_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatID(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpUint(8, sizeof(uint8_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitChangeIDPacket(struct ChangeIDPacket *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->previous_id), BpAlias(8, sizeof(ID), BpXXXProcessID, BpXXXJsonFormatID), "previous_id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->new_id), BpAlias(8, sizeof(ID), BpXXXProcessID, BpXXXJsonFormatID), "new_id");
}

void BpXXXProcessChangeIDPacket(void *data, struct BpProcessorContext *ctx) {
    struct ChangeIDPacket *m = (struct ChangeIDPacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitChangeIDPacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 16, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatChangeIDPacket(void *data, struct BpJsonFormatContext *ctx) {
    struct ChangeIDPacket *m = (struct ChangeIDPacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitChangeIDPacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 16, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeChangeIDPacket(struct ChangeIDPacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessChangeIDPacket((void *)m, &ctx);
    return 0;
}

int DecodeChangeIDPacket(struct ChangeIDPacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessChangeIDPacket((void *)m, &ctx);
    return 0;
}

int JsonChangeIDPacket(struct ChangeIDPacket *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatChangeIDPacket((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitSolenoidStatePacket(struct SolenoidStatePacket *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->id), BpAlias(8, sizeof(ID), BpXXXProcessID, BpXXXJsonFormatID), "id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->state), BpEnum(1, sizeof(SolenoidState)), "state");
}

void BpXXXProcessSolenoidStatePacket(void *data, struct BpProcessorContext *ctx) {
    struct SolenoidStatePacket *m = (struct SolenoidStatePacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitSolenoidStatePacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 9, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatSolenoidStatePacket(void *data, struct BpJsonFormatContext *ctx) {
    struct SolenoidStatePacket *m = (struct SolenoidStatePacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitSolenoidStatePacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 9, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeSolenoidStatePacket(struct SolenoidStatePacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessSolenoidStatePacket((void *)m, &ctx);
    return 0;
}

int DecodeSolenoidStatePacket(struct SolenoidStatePacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessSolenoidStatePacket((void *)m, &ctx);
    return 0;
}

int JsonSolenoidStatePacket(struct SolenoidStatePacket *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatSolenoidStatePacket((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitStagePacket(struct StagePacket *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->system_ready), BpBool(), "system_ready");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->stage), BpEnum(4, sizeof(Stage)), "stage");
}

void BpXXXProcessStagePacket(void *data, struct BpProcessorContext *ctx) {
    struct StagePacket *m = (struct StagePacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitStagePacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 5, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatStagePacket(void *data, struct BpJsonFormatContext *ctx) {
    struct StagePacket *m = (struct StagePacket *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitStagePacket(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 5, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeStagePacket(struct StagePacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessStagePacket((void *)m, &ctx);
    return 0;
}

int DecodeStagePacket(struct StagePacket *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessStagePacket((void *)m, &ctx);
    return 0;
}

int JsonStagePacket(struct StagePacket *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatStagePacket((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitSensorData(struct SensorData *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->node_id), BpAlias(8, sizeof(ID), BpXXXProcessID, BpXXXJsonFormatID), "node_id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->sensor_id), BpUint(4, sizeof(uint8_t)), "sensor_id");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->sensor_type), BpEnum(4, sizeof(SensorType)), "sensor_type");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->sensor_data), BpUint(32, sizeof(uint32_t)), "sensor_data");
}

void BpXXXProcessSensorData(void *data, struct BpProcessorContext *ctx) {
    struct SensorData *m = (struct SensorData *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitSensorData(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 48, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatSensorData(void *data, struct BpJsonFormatContext *ctx) {
    struct SensorData *m = (struct SensorData *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitSensorData(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 48, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeSensorData(struct SensorData *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessSensorData((void *)m, &ctx);
    return 0;
}

int DecodeSensorData(struct SensorData *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessSensorData((void *)m, &ctx);
    return 0;
}

int JsonSensorData(struct SensorData *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatSensorData((void *)m, &ctx);
    return ctx.n;
}